plugins:
  - jekyll-seo-tag

port: 4001

styles:

remote_theme: kosatyi/sjt

exclude:
  - vendor
  - src

javascript:

baseurl: /blogger-php

navigation: false

projects: true

brand: blogger-php
title: Blogger Feed API
description: Simple Blogger Feed Requester
analytics: UA-37629144-1

author:
  name: Stepan Kosatyi
  url: http://www.kosatyi.com/

toolbar:
