remote_theme: kosatyi/sjt

navigation: false
projects: true

baseurl: /blogger-php

brand: blogger-php
title: Blogger Feed API
description: Simple Blogger Feed Requester

author:
  name: Stepan Kosatyi
  url: https://kosatyi.com/
